name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      
      # holy shit why does rojo have so many dependencies (320!!!!) it takes forever to install
      # cargo the new node_modules?
      #- run: sudo apt install libssl-dev
      #- run: cargo install rojo
      #- run: rojo -V
      - run: wget https://github.com/rojo-rbx/rojo/releases/download/v6.2.0/rojo-6.2.0-linux.zip
      - run: unzip rojo-6.2.0-linux.zip
      - run: chmod +x rojo
      - run: ./rojo -V

      - run: npm install -g roblox-ts
      - run: rbxtsc -v

      - run: npm i

      - run: ./.github/versionUpdate.sh
      

      - run: rbxtsc
      
      - run: ./rojo build --output game.rbxlx

      - uses: actions/upload-artifact@v2
        with:
          name: game.rbxlx
          path: game.rbxlx

      - run: "curl -X POST https://apis.roblox.com/universes/v1/3257467677/places/8537272175/versions?versionType=Published -H 'x-api-key: ${{ secrets.ROBLOX_TOKEN }}' -H 'Content-Type: application/xml' --data-binary @game.rbxlx"
        if: ${{ github.ref == 'refs/heads/master' }}


        

